//! Native JS class traits and descriptors shared by all engines.

mod coerce;
mod descriptor;
mod descriptor_cache;
mod native_ref;
mod registry;

pub use coerce::{BufferSource, NativeArg};
pub use descriptor::{
    AccessorDescriptor, AccessorFn, ClassDescriptor, ConstructorFn, FinalizerFn,
    InstanceMethodFn, MethodDescriptor, SymbolDescriptor, WellKnownSymbol,
};
pub use native_ref::{Erased, NativeRef};
pub use registry::{ClassRegistry, ClassScopeExt};

pub use descriptor_cache::class_descriptor;

use std::any::TypeId;

/// Implemented by Rust types that can be wrapped as JS objects.
///
/// # Safety
/// The implementor must guarantee that `Self` is the *exact* type stored in the native object
/// slot. No two `NativeClass` impls may share a slot layout or a class ID. The derive macro
/// upholds this automatically.
pub unsafe trait NativeClass: Sized + Send + 'static {
    /// The JS constructor name — appears in `obj.constructor.name` and stack traces.
    const NAME: &'static str;

    /// Number of internal slots. Always 1 for the `Box<Self>` pointer.
    /// Override only if the backend impl requires extra slots (rare).
    const SLOT_COUNT: usize = 1;

    /// Returns the static [`ClassDescriptor`] for this type.
    /// Generated by the macro; must be a `fn` not a `const` because [`ClassDescriptor`]
    /// contains function pointers which are not const-stable.
    fn descriptor<R: crate::Runtime>() -> &'static ClassDescriptor<R>;

    /// Type-erased identity — used by backends to key their internal maps.
    fn type_id() -> TypeId {
        TypeId::of::<Self>()
    }
}
